config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'users/' => 'users#abc'
  resources :users # ユーザーマイページへのルーティング

  resources :posts do
    resources :likes, only: [:create, :destroy]

    resources :comments, only: [:create]

  end

  get 'posts/:post_id/likes' => 'likes#create'
  get 'posts/:post_id/likes/:id' => 'likes#destroy'

  root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    mount_uploader :image, ImageUploader

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy

    has_many :post_tag_relations, dependent: :destroy
    has_many :tags, through: :post_tag_relations, dependent: :destroy

end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord

    validates :name, presence: true
    has_many :post_tag_relations, dependent: :destroy
    has_many :posts, through: :post_tag_relations, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         mount_uploader :image, ImageUploader

  has_many :posts, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    # deviseコントローラーにストロングパラメータを追加する          
    before_action :configure_permitted_parameters, if: :devise_controller?



    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
  
    def create
      post = Post.find(params[:post_id])
      comment = post.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
  end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
      like = current_user.likes.create(post_id: params[:post_id]) 
      redirect_back(fallback_location: root_path)
    end
  
    def destroy
      like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
      like.destroy
      redirect_back(fallback_location: root_path)
    end
  
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]

    def index
      if params[:search] == nil
        @posts= Post.all
      elsif params[:search] == ''
        @posts= Post.all
      else
        #部分検索
        search = params[:search]
        @posts = Post.where("name LIKE ? OR station LIKE ?OR address LIKE ?OR time LIKE ?OR about LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
      end
        if params[:tag_ids]
        @posts = []
        params[:tag_ids].each do |key, value|
            @posts += Tag.find_by(name: key).posts if value == "1"
        end
        @posts.uniq!
    end
    #以下を追記
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(10)
    #ここまで

      if params[:tag]
        Tag.create(name: params[:tag])
      end

    end

    def new
        @post = Post.new
    end
    
    def create
        post = Post.new(post_params)
        
        post.user_id = current_user.id
        
        if post.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end
    
    def show
      @post = Post.find(params[:id])
      @comments = @post.comments
      @comment = Comment.new
    end

    def edit
      @post = Post.find(params[:id])
    end

    def update
      post = Post.find(params[:id])
      if post.update(post_params)
        redirect_to :action => "show", :id => post.id
      else
        redirect_to :action => "new"
      end
    end

    def destroy
      post = Post.find(params[:id])
      post.destroy
      redirect_to action: :index
    end

      private
    def post_params
        params.require(:post).permit(:name, :station, :address, :time, :about, :image, :lat, :lng, tag_ids: [])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def abc
    @posts = current_user.posts
  end


  def show
    @user = User.find(params[:id]) 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/5ad218c75a.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all'  %>
    <%= javascript_pack_tag 'application'  %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Playball&Clicker+Script&Libre+Baskerville&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
    <h1><%= link_to "Spot Search", posts_path %></h1>
    <div class="header-list">
    <ul>
      <% if user_signed_in? %>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "新規登録", new_user_registration_path %></li>
      <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
      <span class="space">
       <a class="fa-solid fa-file-pen fa-2x" href="posts/new"></a>
      </span>

    </ul>
    </div>
  </header>
  <main>
    
    <%= yield %>
    </main>
    <footer>
      <p> ©2023 Spot Search &emsp; </p>
      <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&display=swap" rel="stylesheet">
    </footer>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@600&display=swap" rel="stylesheet">
  </body>
</html>

app/views/posts/edit.html.erb
<div class="home">
<div class="main">
    <%= form_for @post do |f| %>
        
            <div class='form-group'>
                <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
                    <div class='form-check'>
                        <%= tag.label class: 'form-check-label' do %>
                            <%= tag.check_box class: 'form-check-input' %>
                            <%= tag.text %>
                        <% end %>
                    </div>
                <% end %>
            </div>
            
        <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>

        <div class="field">
        <%= f.label :名前 %>
        <%= f.text_field :name, :size => 30 %>
    </div>

    <div class="field">
        <%= f.label :駅・都市 %>
        <%= f.text_field :station, :size => 30 %>
    </div>

    <div class="field">
        <%= f.label :滞在時間（目安） %>
        <%= f.text_field :time, :size => 30 %>
    </div>

    <div class="field">
        <%= f.label :説明  %>
        <%= f.text_area :about, :size => "30x2" %>
    </div>

    <div class="actions">
        
    <%= f.label :lat,"緯度" %>
    <%= f.text_field :lat,:value =>"緯度", id: :lat %>
    <%= f.label :lng,"経度" %>
    <%= f.text_field :lng,:value =>"経度", id: :lng %>

　</div>

  

  
  <h2>Map</h2>
  
  <input id="address" type="textbox" value="">
  <input type="button" value="検索" onclick="codeAddress()">
  <p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
  <div id='map'></div>
  
  <style>
  #map {
    height: 600px;
    width: 600px;
  }
  </style>
  
  <script>
  //初期マップの設定
  let map
  let marker
  function initMap(){
    geocoder = new google.maps.Geocoder()
  
    map = new google.maps.Map(document.getElementById('map'), {
      center:  {lat: 35.6803997, lng:139.7690174},  //東京
      zoom: 15,
      
    });
  }
  
  //検索後のマップ作成
  let geocoder
  let aft
  function codeAddress(){
    let inputAddress = document.getElementById('address').value;
    geocoder.geocode( { 'address': inputAddress}, function(results, status) {
      if (status == 'OK') {
          //マーカーが複数できないようにする
          if (aft == true){
              marker.setMap(null);
          }
  
          //新しくマーカーを作成する
          map.setCenter(results[0].geometry.location);
              marker = new google.maps.Marker({
              map: map,
              position: results[0].geometry.location,
              draggable: true	// ドラッグ可能にする
          });
  
          //二度目以降か判断
          aft = true
  
          //検索した時に緯度経度を入力する
          document.getElementById('lat').value = results[0].geometry.location.lat();
          document.getElementById('lng').value = results[0].geometry.location.lng();
  
          // マーカーのドロップ（ドラッグ終了）時のイベント
          google.maps.event.addListener( marker, 'dragend', function(ev){
              // イベントの引数evの、プロパティ.latLngが緯度経度
              document.getElementById('lat').value = ev.latLng.lat();
              document.getElementById('lng').value = ev.latLng.lng();
          });
      } else {
        alert('該当する結果がありませんでした：' + status);
      }
    });   
  }
        
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYUm_VavnX9kGujsE2QLXawIr5CaY3tzo&callback=initMap" async defer></script>


        <%= f.submit "編集する" %>
    <% end %>
</div>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<div class="home">
  <div class="home2">
    <h2>場所を検索</h2>
    <br>
    <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
    
      <%= text_field_tag :search %>
      <style>
      #search {
        height: 30px;
        width: 70%;
        font-size: 18px
      }
      </style>
      <input type="submit" value="検索" class="button">
      

    <% end %>
<br>
    <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
      <%= text_field_tag :tag %>
      <%= submit_tag 'タグを追加' %>
    <% end %>

    <div class="radioArea" id="makeImg">
      <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
        <% Tag.all.each do |t| %>
            <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
        <% end %>
      
        <input type="submit" value="検索" class="button">
      <% end %>
    </div>
    <br>
    <% if user_signed_in? %>
      <%= link_to "マイページへ", user_path(current_user.id) %>
      <br><%= link_to "投稿一覧へ", users_path %>
    <% end %>

    <br><%= link_to "新規投稿へ", new_post_path %>
    </div>
  <div class="map-home">

    <h2><br>spot一覧</h2>
<br>
      <div id='map'></div>

    <style>
    #map {
      height: 500px;
      width: 600px;
    }
    </style>

    <!-- js部分 -->
    <script>
        function initMap() {

          //初期表示位置
          let latlng = new google.maps.LatLng(38.60, 139.5);
          //デザイン
          let styles = [
              {
              stylers: [
                { "saturation": 0 },
                { "lightness": 0 }
                ]
              }
              ];

          let map = new google.maps.Map(document.getElementById('map'), {
              zoom: 5.5,
              styles: styles,
              center: latlng
          });
          let transitLayer = new google.maps.TransitLayer();
          transitLayer.setMap(map);

    //複数マーカー ここから
          <% @posts.each do |post|%>
            ( function() { 
              let markerLatLng = { lat: <%= post.lat %>, lng: <%= post.lng %> }; // 緯度経度のデータ作成
              let marker = new google.maps.Marker({ 
                position: markerLatLng, 
                map: map 
              });
    //マーカーをクリックしたとき、詳細情報を表示
              let infowindow = new google.maps.InfoWindow({
                position: markerLatLng,
                content: "<a href='<%= post_url(post.id) %>' target='_blank'><h5><%= post.name %></h5></a>"
      
              }); //ここで詳細ページへのリンクを表示させる
              marker.addListener('click', function() {
                infowindow.open(map, marker);
              });

          })();
          <% end %>
          //複数マーカー ここまで  
      }
    </script>


    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYUm_VavnX9kGujsE2QLXawIr5CaY3tzo&callback=initMap" async defer></script>
  </div>
</div>
  <div class="search">

  <div class="page">
    <br>
      <%= page_entries_info @posts %>
      <br><%= paginate @posts %>
  </div>

  <div class="posts-container">
      <% @posts.each do |t| %>
        <div class="post">
        <%= t.user.name %><br>

          <%= image_tag t.image_url, size: "250x200" if t.image? %><br>
          <%= t.name %><br>
          <%= t.station %><br>
          <%= t.address %>
          <%= t.time %><br>
          <%= t.about %><br>

          <% if user_signed_in? %>
              <% if current_user.already_liked?(t) %>
                  <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                    <i class="fas fa-heart"></i><%= t.likes.count %>
                  <% end %>
              <% else %>
                  <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                    <i class="far fa-heart"></i><%= t.likes.count %>
                  <% end %>
              <% end %>
          <% else %>
      <i class="far fa-heart"></i><%= t.likes.count %>
      <% end %>
          <%= t.created_at %>
      <br>
          <%= link_to "詳細へ", post_path(t.id) %>
        <%= link_to "編集する", edit_post_path(t.id) %>
        <%= button_to "削除する", post_path(t.id), method: :delete %>
        </div>
        <% end %>
        </div>
    <div class="space2">
      <p><%= paginate @posts %></p>

  
    </div>
</div>

app/views/posts/new.html.erb
<div class="home">
<div class="main">
  <h2>新規投稿</h2>
  <br>
  <%= form_for @post do |f| %>

          <div class='form-group'>
              <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
                  <div class='form-check'>
                      <%= tag.label class: 'form-check-label' do %>
                          <%= tag.check_box class: 'form-check-input' %>
                          <%= tag.text %>
                      <% end %>
                  </div>
              <% end %>
          </div>
          
      <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>

      <div class="field">
          <%= f.label :名前 %>
          <%= f.text_field :name, :size => 30 %>
      </div>

      <div class="field">
          <%= f.label :駅・都市 %>
          <%= f.text_field :station, :size => 30 %>
      </div>

    

      <div class="field">
          <%= f.label :滞在時間（目安） %>
          <%= f.text_field :time, :size => 30 %>
      </div>

      <div class="field">
          <%= f.label :説明  %>
          <%= f.text_area :about, :size => "30x2" %>
      </div>

      <div class="actions">
        
        <%= f.label :lat,"緯度" %>
        <%= f.text_field :lat,:value =>"緯度", id: :lat %>
        <%= f.label :lng,"経度" %>
        <%= f.text_field :lng,:value =>"経度", id: :lng %>
    
    　</div>

      
    
      
      <h2>Map</h2>
      
      <input id="address" type="textbox" value="">
      <input type="button" value="検索" onclick="codeAddress()">
      <p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
      <div id='map'></div>
      
      <style>
      #map {
        height: 600px;
        width: 600px;
      }
      </style>
      
      <script>
      //初期マップの設定
      let map
      let marker
      function initMap(){
        geocoder = new google.maps.Geocoder()
      
        map = new google.maps.Map(document.getElementById('map'), {
          center:  {lat: 35.6803997, lng:139.7690174},  //東京
          zoom: 15,
          
        });
      }
      
      //検索後のマップ作成
      let geocoder
      let aft
      function codeAddress(){
        let inputAddress = document.getElementById('address').value;
        geocoder.geocode( { 'address': inputAddress}, function(results, status) {
          if (status == 'OK') {
              //マーカーが複数できないようにする
              if (aft == true){
                  marker.setMap(null);
              }
      
              //新しくマーカーを作成する
              map.setCenter(results[0].geometry.location);
                  marker = new google.maps.Marker({
                  map: map,
                  position: results[0].geometry.location,
                  draggable: true	// ドラッグ可能にする
              });
      
              //二度目以降か判断
              aft = true
      
              //検索した時に緯度経度を入力する
              document.getElementById('lat').value = results[0].geometry.location.lat();
              document.getElementById('lng').value = results[0].geometry.location.lng();
      
              // マーカーのドロップ（ドラッグ終了）時のイベント
              google.maps.event.addListener( marker, 'dragend', function(ev){
                  // イベントの引数evの、プロパティ.latLngが緯度経度
                  document.getElementById('lat').value = ev.latLng.lat();
                  document.getElementById('lng').value = ev.latLng.lng();
              });
          } else {
            alert('該当する結果がありませんでした：' + status);
          }
        });   
      }
            
      </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYUm_VavnX9kGujsE2QLXawIr5CaY3tzo&callback=initMap" async defer></script>
      <%= f.submit "投稿する" %>
  <% end %>

  <%= link_to "一覧に戻る", posts_path %>
</div>
</div>

app/views/posts/show.html.erb
<div class="home">
<div class="main">
  <h1> <p><%= @post.name %></p></h1>
  <h3>場所</h3>
  <div class="post">
    <p><%= @post.station %></p>
    <p><%= @post.address %></p>
    <p><%= @post.time %></p>
    <p><%= @post.about %></p>
    <p><%= @post.created_at %></p>

  <% if user_signed_in? %>
        <% if current_user.already_liked?(@post) %>
          <%= link_to post_like_path(@post), method: :delete do %>
            <i class="fas fa-heart"></i><%= @post.likes.count %>
          <% end %>
        <% else %>
          <%= link_to post_likes_path(@post), method: :post do %>
            <i class="far fa-heart"></i><%= @post.likes.count %>
          <% end %>
        <% end %>
      <% else %>
      <i class="far fa-heart"></i><%= @post.likes.count %>
      <% end %>

  <%= link_to "編集する", edit_post_path(@post.id) %>
  </div>

  <div id='map'></div>

  <style>
  #map {
    height: 600px;
    width: 100%;
  }
  </style>

  <!-- js部分 -->
  <script>
  //初期マップの設定
  let map
  let marker
  function initMap(){
    geocoder = new google.maps.Geocoder()

    map = new google.maps.Map(document.getElementById('map'), {
      center:  {lat: <%= @post.lat %>, lng: <%= @post.lng %>},
      zoom: 15,
    });

    marker = new google.maps.Marker({
      position:  {lat: <%= @post.lat %>, lng: <%= @post.lng %>},
      map: map
    });
  }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYUm_VavnX9kGujsE2QLXawIr5CaY3tzo&callback=initMap" async defer></script>

  <br>
  <div class="comment-wrapper">
    <p>コメント一覧</p>
    <% @comments.each do |c| %>
      <div>
        <%= c.user.name unless c.user.blank? %>
        <br>
        <%= c.content %>
      </div>
        <br>
    <% end %>

    <% if user_signed_in? %>
      <%= form_with(model: [@post, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
          <i class="far fa-comments"></i> コメントする
        <% end %>
      <% end %>
    <% end %>
  </div>

  <%= link_to "スポット一覧に戻る", posts_path %>
</div>
</div>

app/views/users/abc.html.erb
<div class="home">
<div class="main">
  <h2>ユーザーの投稿一覧</h2>
  <% @posts.each do |t| %>
    <%= t.user.name %>
    <%= t.name %>
  <% end %>

  <%= link_to "スポット一覧に戻る", posts_path %>
</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="home">
  <div class="main">
    <h2>マイページ</h2>
    <br>
    <p>メールアドレス : <%= @user.email %></p>
    <%= image_tag @user.image_url, size: "150x120" if @user.image? %>
    <p>名前 : <%= @user.name %></p>
    <p>プロフィール : <%= @user.profile %></p>

    <% if current_user.id == @user.id %>
      <%= link_to "編集する", edit_user_registration_path %>
    <% end %>
    
      <!-- 以下はいいね機能を実装している場合-->
      <h2><br>お気に入り一覧</h2>
      <% @user.liked_posts.each do |t| %>
        <div class="likes">
        <%= t.user.name %>
        <%= t.name %>
        <%= link_to "詳細へ", post_path(t.id) %>
        </div>
      <% end %>
      <!-- ここまで-->
      <br>
      <%= link_to "スポット一覧に戻る", posts_path %>
  </div>
</div>